controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

igreja:
    path: /igrejas
    controller: App\Controller\Igrejas::index
    
